# Generated by Django 2.2.5 on 2019-10-09 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('outline', models.TextField()),
                ('prerequisites', models.TextField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('private', models.BooleanField()),
                ('tags', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('fee', models.FloatField()),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_approved_by', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
