# Generated by Django 2.2.5 on 2019-10-09 22:13

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=course.models.gen_pic_path),
        ),
    ]
