# Generated by Django 2.2.5 on 2019-10-10 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191010_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
