# Generated by Django 2.2.5 on 2019-10-10 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20191010_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
