# Generated by Django 2.2.5 on 2019-10-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20191010_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
