# Generated by Django 2.2.5 on 2019-12-03 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_content_contentaccess_prerequisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentaccess',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Content'),
        ),
    ]
