# Generated by Django 2.2.5 on 2019-12-03 19:32

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20191204_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(upload_to=course.models.gen_pic_path),
        ),
    ]
