# Generated by Django 2.2.5 on 2019-12-03 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20191204_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_course_id', to='course.Course'),
        ),
    ]
