# Generated by Django 2.2.5 on 2019-12-03 20:58

import course.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20191204_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('content_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=course.models.gen_pic_path)),
                ('file_type', models.BooleanField()),
                ('serial', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('course_idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents_course_id', to='course.Course')),
            ],
        ),
    ]
