# Generated by Django 2.2.5 on 2019-12-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_contents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contents',
        ),
    ]
