# Generated by Django 2.2.5 on 2019-12-04 11:19

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_delete_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(upload_to=course.models.contents_file_path),
        ),
    ]
