# Generated by Django 2.2.5 on 2019-12-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_auto_20191204_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
