# Generated by Django 2.2.5 on 2019-12-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20191204_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['serial']},
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(default='Beginner', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
