# Generated by Django 2.2.5 on 2019-12-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
